### PR TITLE
Added Bubble Sort in Python

### PR DESCRIPTION
**Pull request by Casey-McCray**
Resolves Issue #94 

### Description
Added Bubble Sort in Python/Casey-McCray.py

### Technical Specifications
Made in Python 3

### How to run
Copy the code into your terminal or use an IDE to run the code.
Pass the array to the function and it will sort it for you :D 

### Checklist
- [x] Code compiles correctly.
- [x] Changes are tested properly.
- [x] Added the README / documentation, if necessary.
- [x] Followed the Contributing guidelines.
- [x] Resolved merge conflicts, if any.

### CODE REVIEW

**Comment by Casey-McCray** [comment]
Resolves Issue #92  

### Description
Added Binary Search in CPP/Casey-McCray.cpp

### How to run
Download the file.
Run it using your favorite compiler.
Pass the array to the function and it will Search the element you want it to for you :D 

### Checklist
- [x] Code compiles correctly.
- [x] Changes are tested properly.
- [x] Added the README / documentation, if necessary.
- [x] Followed the Contributing guidelines.
- [x] Resolved merge conflicts, if any.

**Comment by mahim23** [comment]
@Casey-McCray These are two separate issues you've referenced. Please create separate pull requests for them.

**Comment by mahim23** [comment]
@Casey-McCray Also, after claiming the issue, kindly wait for an approval to work on it.

**Comment by Casey-McCray** [comment]
> @Casey-McCray Also, after claiming the issue, kindly wait for an approval to work on it.

I'm sorry I didn't know I had to wait for an approval

**Comment by Casey-McCray** [comment]
> @Casey-McCray These are two separate issues you've referenced. Please create separate pull requests for them.

I tried to do that but I couldn't understand how to separate multiple commits into different PRs,
Can you help me?

**Comment by mahim23** [comment]
> 
> 
> > @Casey-McCray These are two separate issues you've referenced. Please create separate pull requests for them.
> 
> I tried to do that but I couldn't understand how to separate multiple commits into different PRs,
> Can you help me?

You can either wait for the first PR to be merged and then open a new one, or work on a different branch for the second issue and make a PR from that branch.

**Comment by mahim23** [comment]
@Casey-McCray I'll have to close this PR for a lack of response.

**Pull request closed without merging**
