### PR TITLE
Responsive design

### PR DESCRIPTION
**Pull request by 1337M0nst3r**
Resolves Issue #164 

### Description
Make /development/static_to_responsive/static.html responsive by linking a css stylesheet to it with css rules to make it responsive(css grid).

### Screenshots
2018-10-13-205452_1366x768_scrot
2018-10-13-205818_1366x768_scrot
2018-10-13-205833_1366x768_scrot

### Technical Specifications
Language: CSS

### How to run
open /development/static_to_responsive/static.html in a browser

### Checklist
- [x] Code compiles correctly.
- [x] Changes are tested properly.
- [x] Followed the Contributing guidelines.

### CODE REVIEW

**Comment by pvgupta24** [comment]
@1337M0nst3r any updates?

**Comment by 1337M0nst3r** [comment]
@mishal23 @pvgupta24 will do them in one hour, sorry for late reply

**Comment by 1337M0nst3r** [comment]
is this ok?

**Comment by nimbus98** [comment]
Yes, this should do I believe

**Comment by mishal23** [comment]
Great, thanks for contributing @1337M0nst3r

**Pull request merged**
