### PR TITLE
Convert strings to URL Slugs #209

### PR DESCRIPTION
**Pull request by SergiyGolov**
Resolves Issue #209
### Description
The function  replaces uppercase letters with lowercase + accents like "éèàüöä" with "eeauoa" + replace "&" with "and" + filters all non alphanumeric characters and replaces blank spaces with "-"

### How to run
Include ``string_to_url_slug.js`` in your html page and use the ``string_to_url_slug(title)`` javascript function to get the hyphenated version of the title, an example is provided in the ``example.html`` file

### Checklist
- [x] Code compiles correctly.
- [x] Changes are tested properly.
- [x] Added the README / documentation, if necessary.
- [x] Followed the Contributing guidelines.
- [x] Resolved merge conflicts, if any.

### CODE REVIEW

**Comment by mishal23** [comment]
Hi @SergiyGolov , thanks for the contribution, great work!
Please change the PR description according to the [template](https://github.com/WebClub-NITK/Hacktoberfest-2k18/blob/master/.github/PULL_REQUEST_TEMPLATE.md)

**Comment by mishal23** [comment]
@SergiyGolov any updates?

**Comment by SergiyGolov** [comment]
Is it ok now?

**Comment by mishal23** [comment]
Yes @SergiyGolov , Thanks for contributing 😄

**Pull request merged**
