### PR TITLE
Add process scheduling

### PR DESCRIPTION
**Pull request by 1337M0nst3r**
Resolves Issue #242 

### Description
Implemented round robin process scheduling algorithm

### Technical Specifications
Made in C++

### Screenshots (if required)
2018-10-21-193732_1366x768_scrot
2018-10-21-193740_1366x768_scrot
2018-10-21-193749_1366x768_scrot
2018-10-21-193755_1366x768_scrot
2018-10-21-193805_1366x768_scrot

### How to run
Open systems/os/process_scheduling/rr/c++/rr.cpp in any C++ IDE and press build & run OR open a terminal go to systems/process_scheduling/rr/c++/ and type: g++ rr.cpp && ./a.out then press enter

### Checklist
- [x ] Code compiles correctly.
- [x ] Changes are tested properly.
- [x ] Followed the Contributing guidelines.

### CODE REVIEW

**Comment by Ram-Aditya** [comment]
@1337M0nst3r Are you sure you have implemented the algorithm correctly? Consider your first example.
1. Many processes do not have the scheduled times. 
2. Why does Process 0 have a waiting time of 32microseconds? Let the time start from 0. Now, what is actually supposed to happen for process 0 is as follows: Process 0 arrives at time 0 microseconds, and is given access to CPU. Thus it is first scheduled at time 0 microseconds. It executed on CPU for a time quantum of 2 microseconds. Now the time is 2 microseconds. No other process has arrived yet. Thus process 0 is given access to CPU again and executed on the CPU for 1 microsecond and terminates. This is because the cumulative time it has executed on the CPU is 3 microseconds which is equal to its burst time. Thus its waiting time is 0 microseconds. and schedule times are 0 and 2 microseconds as it was scheduled the first time at 0 microseconds and then again at 2 microseconds.

These are a few of the many issues with the implementation. Kindly recheck your implementation and feel free to clear any confusions/misinterpretations that may have been the cause of the issues.

**Comment by 1337M0nst3r** [comment]
I can fix the schedule times problem but you said to initialize the processes's arrival time with random values between 0 and 50s what's their purpose?

**Comment by 1337M0nst3r** [comment]
Nevermind I got it, now what should I do? Create another pull request?

**Comment by Ram-Aditya** [comment]
@1337M0nst3r  Yes, please create a new PR.

**Pull request closed without merging**
