### PR TITLE
Adding FCFS scheduling in C++

### PR DESCRIPTION
**Pull request by insane-abhi**
image

### CODE REVIEW

**Comment by Ram-Aditya** [comment]
@insane-abhi Please read the issue details carefully. You need to show 5 sample inputs and outputs. Also, please edit your pull request and follow the pull request template  ( https://github.com/WebClub-NITK/Hacktoberfest-2k18/blob/master/.github/PULL_REQUEST_TEMPLATE.md ).

**Comment by insane-abhi** [comment]
Edited the pull request according to template

**Comment by Ram-Aditya** [comment]
@insane-abhi You still haven't followed the Pull Request template whose link I have mentioned in my comment above. Also, you are supposed to attach screenshots of 5 inputs and their corresponding outputs.

**Comment by insane-abhi** [comment]
@Ram-Aditya Pls see the readme.md, it's according to template

**Comment by mahim23** [comment]
@insane-abhi the README.md contents that you have put should be there in the PR description. Please do the needful so that the PR can be accepted.

**Comment by insane-abhi** [comment]
Resolves Issue #16

### Description
Implements the First-Come, First-Serve process scheduling algorithm. 
Takes input of arrival time(seconds) and burst time(microseconds) and 
returns array sorted according to arrival time corresponding to the time they were scheduled.


### Technical Specifications
Implemented in C++

### Screenshots
Sample-Inputs: 
### 1
<br><br>
alt text
<br><br> 
### 2 <br><br>
alt text
<br><br>
### 3 <br><br>
alt text
<br><br>
### 4 <br><br>
alt text
<br><br>
### 5 <br><br>
alt text
<br><br>
### How to run
Compile and run,
it randomly selects 10 proccess arrival time and burst time and provides output.

### Checklist
-  Code compiles correctly.
-  Changes are tested properly.
-  Added the README / documentation.

**Comment by insane-abhi** [comment]
@mahim23 Done the same

**Comment by Ram-Aditya** [comment]
@insane-abhi  In the output, the process-ID of the scheduled process must be printed. But in your outputs, the arrival time of the processes that arrived are being printed. Please make the minor change to the code.

**Comment by insane-abhi** [comment]
Resolves Issue #16

### Description
Implements the First-Come, First-Serve process scheduling algorithm. 
Takes input of arrival time(seconds) and burst time(microseconds) and 
returns array sorted according to arrival time corresponding to the time they were scheduled.


### Technical Specifications
Implemented in C++

### Screenshots
Sample-Inputs: 
### 1
<br><br>
alt text
<br><br> 
### 2 <br><br>
alt text
<br><br>
### 3 <br><br>
alt text
<br><br>
### 4 <br><br>
alt text
<br><br>
### 5 <br><br>
alt text
<br><br>
### How to run
Compile and run,
it randomly selects 10 proccess arrival time and burst time and provides output.

### Checklist
-  Code compiles correctly.
-  Changes are tested properly.
-  Added the README / documentation.

**Comment by insane-abhi** [comment]
@Ram-Aditya  updates made in the code, kindly see it.

**Comment by Ram-Aditya** [comment]
@insane-abhi Good job!

**Pull request merged**
